# Generated by Django 5.0.1 on 2024-01-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=67, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
